export const vehicles = [
  // Cars
  {
    id: 1,
    name: "Maruti Swift",
    brand: "Maruti",
    category: "Cars",
    price: 550000,
    year: 2024,
    mileage: 23,
    image: "/sporty-red-hatchback.png",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1.2L",
    description: "Compact hatchback with great mileage and reliable performance.",
    features: ["Power Steering", "ABS", "Dual Airbags", "Air Conditioning"],
    variants: [
      { name: "LXi (O)", price: 550000, transmission: "Manual" },
      { name: "VXi", price: 620000, transmission: "Manual" },
      { name: "VXi (O)", price: 700000, transmission: "Automatic" },
      { name: "ZXi", price: 750000, transmission: "Automatic" },
    ],
    colors: ["Pearl Red", "Silver", "Black", "White", "Blue"],
    galleryImages: [
      "/sporty-red-hatchback.png",
      "/maruti-swift-side-view.jpg",
      "/maruti-swift-interior.png",
      "/maruti-swift-dashboard.jpg",
    ],
    specifications: {
      bodyType: "Hatchback",
      fuelTankCapacity: "42L",
      seating: "5",
      bootSpace: "265L",
      acceleration: "0-100 km/h in 10.2s",
      topSpeed: "180 km/h",
      groundClearance: "190mm",
      length: "3.84m",
      width: "1.66m",
      height: "1.50m",
    },
  },
  {
    id: 2,
    name: "Tata Nexon EV",
    brand: "Tata",
    category: "EVs",
    price: 1500000,
    year: 2024,
    mileage: 350,
    image: "/tata-nexon-electric-vehicle.jpg",
    fuel: "Electric",
    transmission: "Automatic",
    engine: "Electric Motor",
    description: "Premium electric SUV with excellent range and performance.",
    features: ["Fast Charging", "Tesla-like Interface", "All-Wheel Drive", "Premium Interior"],
    variants: [
      { name: "Smart", price: 1500000, transmission: "Automatic" },
      { name: "Plus", price: 1800000, transmission: "Automatic" },
      { name: "Pro", price: 2100000, transmission: "Automatic" },
    ],
    colors: ["Glacier White", "Dark Grey", "Black", "Red"],
    galleryImages: [
      "/tata-nexon-electric-vehicle.jpg",
      "/tata-nexon-ev-side.jpg",
      "/tata-nexon-ev-interior.jpg",
      "/tata-nexon-ev-charging.jpg",
    ],
    specifications: {
      bodyType: "Compact SUV",
      batteryCapacity: "40.5 kWh",
      seating: "5",
      bootSpace: "350L",
      acceleration: "0-100 km/h in 9.5s",
      topSpeed: "160 km/h",
      groundClearance: "200mm",
      length: "4.0m",
      width: "1.82m",
      height: "1.61m",
      chargingTime: "6.5 hours (Fast Charger)",
    },
  },
  {
    id: 3,
    name: "Hyundai Creta",
    brand: "Hyundai",
    category: "Cars",
    price: 1200000,
    year: 2024,
    mileage: 17,
    image: "/hyundai-creta-suv.png",
    fuel: "Diesel",
    transmission: "Automatic",
    engine: "1.5L",
    description: "Stylish compact SUV with modern features and comfort.",
    features: ["Touchscreen", "Panoramic Sunroof", "Cruise Control", "6 Airbags"],
    variants: [
      { name: "E", price: 1200000, transmission: "Manual" },
      { name: "S", price: 1400000, transmission: "Automatic" },
      { name: "SX", price: 1700000, transmission: "Automatic" },
      { name: "SX(O)", price: 1950000, transmission: "Automatic" },
    ],
    colors: ["Polar White", "Titan Grey", "Black Obsidian", "Fiery Red", "Mystic Blue"],
    galleryImages: [
      "/hyundai-creta-suv.png",
      "/hyundai-creta-exterior.jpg",
      "/hyundai-creta-interior.jpg",
      "/hyundai-creta-dashboard.jpg",
    ],
    specifications: {
      bodyType: "Compact SUV",
      fuelTankCapacity: "50L",
      seating: "5",
      bootSpace: "395L",
      acceleration: "0-100 km/h in 10.5s",
      topSpeed: "190 km/h",
      groundClearance: "200mm",
      length: "4.27m",
      width: "1.83m",
      height: "1.62m",
    },
  },
  {
    id: 4,
    name: "Honda CB350",
    brand: "Honda",
    category: "Bikes",
    price: 180000,
    year: 2024,
    mileage: 35,
    image: "/honda-cb350-motorcycle.jpg",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "350cc",
    description: "Classic retro-styled motorcycle with excellent build quality.",
    features: ["ABS", "Dual Exhausts", "Alloy Wheels", "Keyless Ignition"],
    variants: [
      { name: "Standard", price: 180000, transmission: "Manual" },
      { name: "Deluxe", price: 200000, transmission: "Manual" },
    ],
    colors: ["Black", "Silver", "Pearl Red", "Matte Blue"],
    galleryImages: [
      "/honda-cb350-motorcycle.jpg",
      "/honda-cb350-side-view.jpg",
      "/honda-cb350-engine.jpg",
      "/honda-cb350-detail.jpg",
    ],
    specifications: {
      bodyType: "Cruiser",
      engineType: "Single Cylinder, Air Cooled",
      power: "20.8 bhp",
      torque: "30 Nm",
      brakeType: "Disc",
      tyreFront: "100/90-18",
      tyreRear: "120/80-18",
      seatHeight: "790mm",
      fuelTankCapacity: "15L",
    },
  },
  {
    id: 5,
    name: "Bajaj Pulsar 150",
    brand: "Bajaj",
    category: "Bikes",
    price: 95000,
    year: 2024,
    mileage: 45,
    image: "/bajaj-pulsar-150-bike.jpg",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "150cc",
    description: "Sporty and affordable motorcycle for daily commuting.",
    features: ["Digital Display", "ABS", "Alloy Wheels", "LED Headlamp"],
    variants: [
      { name: "Standard", price: 95000, transmission: "Manual" },
      { name: "Neon", price: 105000, transmission: "Manual" },
    ],
    colors: ["Black", "Silver", "Red", "Blue", "Green"],
    galleryImages: [
      "/bajaj-pulsar-150-bike.jpg",
      "/bajaj-pulsar-150-side.jpg",
      "/bajaj-pulsar-150-front.jpg",
      "/bajaj-pulsar-150-detail.jpg",
    ],
    specifications: {
      bodyType: "Sports",
      engineType: "Single Cylinder, Air Cooled",
      power: "14 bhp",
      torque: "13.4 Nm",
      brakeType: "Disc",
      tyreFront: "80/100-17",
      tyreRear: "100/80-17",
      seatHeight: "790mm",
      fuelTankCapacity: "15L",
    },
  },
  {
    id: 6,
    name: "Hero Pleasure+",
    brand: "Hero",
    category: "Scooters",
    price: 62000,
    year: 2024,
    mileage: 65,
    image: "/hero-pleasure-scooter.jpg",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "110cc",
    description: "Fuel-efficient and comfortable automatic scooter.",
    features: ["Automatic Transmission", "Digital Console", "Under-seat Storage", "LED Lights"],
    variants: [
      { name: "Standard", price: 62000, transmission: "Automatic" },
      { name: "Plus", price: 72000, transmission: "Automatic" },
    ],
    colors: ["Black", "Silver", "Red", "White"],
    galleryImages: [
      "/hero-pleasure-scooter.jpg",
      "/hero-pleasure-scooter-side.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Automatic Scooter",
      engineType: "Single Cylinder, Air Cooled",
      power: "8 bhp",
      torque: "8.2 Nm",
      brakeType: "Drum",
      tyreSize: "90/90-12",
      seatHeight: "775mm",
      fuelTankCapacity: "5.2L",
    },
  },
  {
    id: 7,
    name: "Kia Sonet",
    brand: "Kia",
    category: "Cars",
    price: 800000,
    year: 2024,
    mileage: 19,
    image: "/kia-sonet-compact-suv.jpg",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "1.2L",
    description: "Compact SUV with bold design and premium features.",
    features: ["Turbo Petrol", "Touchscreen Infotainment", "Multiple Airbags", "Power Windows"],
    variants: [
      { name: "HT Line", price: 800000, transmission: "Manual" },
      { name: "HTK", price: 950000, transmission: "Automatic" },
      { name: "HTK+", price: 1100000, transmission: "Automatic" },
      { name: "HTX", price: 1300000, transmission: "Automatic" },
    ],
    colors: ["Glacier White", "Sparkling Silver", "Phantom Black", "Cherry Red", "Sapphire Blue"],
    galleryImages: [
      "/kia-sonet-compact-suv.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Compact SUV",
      fuelTankCapacity: "50L",
      seating: "5",
      bootSpace: "392L",
      acceleration: "0-100 km/h in 10s",
      topSpeed: "190 km/h",
      groundClearance: "200mm",
      length: "4.12m",
      width: "1.79m",
      height: "1.59m",
    },
  },
  {
    id: 8,
    name: "BYD Atto 3",
    brand: "BYD",
    category: "EVs",
    price: 2500000,
    year: 2024,
    mileage: 400,
    image: "/byd-atto-3-electric-suv.jpg",
    fuel: "Electric",
    transmission: "Automatic",
    engine: "Electric Motor",
    description: "Premium electric SUV with cutting-edge technology.",
    features: ["Dual Motor", "Panoramic Sunroof", "ADAS", "5-Star Safety"],
    variants: [
      { name: "Standard Range", price: 2500000, transmission: "Automatic" },
      { name: "Extended Range", price: 2900000, transmission: "Automatic" },
    ],
    colors: ["Pearl White", "Midnight Black", "Azure Blue", "Titanium Grey"],
    galleryImages: [
      "/byd-atto-3-electric-suv.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Premium Electric SUV",
      batteryCapacity: "60 kWh",
      seating: "5",
      bootSpace: "440L",
      acceleration: "0-100 km/h in 8.5s",
      topSpeed: "180 km/h",
      groundClearance: "210mm",
      length: "4.4m",
      width: "1.85m",
      height: "1.68m",
      chargingTime: "5 hours (Fast Charger)",
    },
  },
  {
    id: 9,
    name: "Hero Splendor",
    brand: "Hero",
    category: "Bikes",
    price: 68000,
    year: 2024,
    mileage: 90,
    image: "/hero-splendor-bike.jpg",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "97cc",
    description: "India's most trusted commuter motorcycle.",
    features: ["Fuel Efficient", "i3S Technology", "Single Cylinder", "Tubeless Tyres"],
    variants: [
      { name: "Standard", price: 68000, transmission: "Manual" },
      { name: "Plus", price: 78000, transmission: "Manual" },
    ],
    colors: ["Black", "Silver", "Red", "Blue"],
    galleryImages: [
      "/hero-splendor-bike.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Commuter",
      engineType: "Single Cylinder, Air Cooled",
      power: "8.36 bhp",
      torque: "8.05 Nm",
      brakeType: "Drum",
      tyreFront: "80/100-17",
      tyreRear: "100/90-17",
      seatHeight: "790mm",
      fuelTankCapacity: "13L",
    },
  },
  {
    id: 10,
    name: "Ather 450X",
    brand: "Ather",
    category: "Scooters",
    price: 145000,
    year: 2024,
    mileage: 100,
    image: "/ather-450x-electric-scooter.jpg",
    fuel: "Electric",
    transmission: "Automatic",
    engine: "Electric Motor",
    description: "Premium electric scooter with smart features.",
    features: ["Fast Charging", "Smart Display", "OTA Updates", "App Connectivity"],
    variants: [
      { name: "450X", price: 145000, transmission: "Automatic" },
      { name: "450 Plus", price: 165000, transmission: "Automatic" },
    ],
    colors: ["Gunmetal Grey", "Pearl White", "Midnight Black", "Forest Green"],
    galleryImages: [
      "/ather-450x-electric-scooter.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Electric Scooter",
      batteryCapacity: "7.36 kWh",
      power: "11.4 kW",
      range: "116 km",
      acceleration: "0-40 km/h in 5.1s",
      topSpeed: "80 km/h",
      tyreSize: "10 Inch",
      seatHeight: "790mm",
      chargingTime: "6.5 hours",
    },
  },
  {
    id: 11,
    name: "MG Hector",
    brand: "MG",
    category: "Cars",
    price: 1400000,
    year: 2024,
    mileage: 16,
    image: "/mg-hector-suv.jpg",
    fuel: "Petrol",
    transmission: "Automatic",
    engine: "1.5L Turbo",
    description: "Feature-rich 7-seater SUV with modern technology.",
    features: ["10.4 inch Touchscreen", "Connected Car", "Sunroof", "ISOFIX"],
    variants: [
      { name: "Style", price: 1400000, transmission: "Manual" },
      { name: "Super", price: 1600000, transmission: "Automatic" },
      { name: "Smart", price: 1900000, transmission: "Automatic" },
      { name: "Sharp", price: 2200000, transmission: "Automatic" },
    ],
    colors: ["Pearl White", "Ebony Black", "Stealth Grey", "Cherry Red", "Sapphire Blue"],
    galleryImages: [
      "/mg-hector-suv.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "7-seater SUV",
      fuelTankCapacity: "50L",
      seating: "7",
      bootSpace: "480L",
      acceleration: "0-100 km/h in 9.6s",
      topSpeed: "195 km/h",
      groundClearance: "210mm",
      length: "4.73m",
      width: "1.84m",
      height: "1.70m",
    },
  },
  {
    id: 12,
    name: "TVS Apache RR310",
    brand: "TVS",
    category: "Bikes",
    price: 280000,
    year: 2024,
    mileage: 32,
    image: "/tvs-apache-rr310-sport-bike.jpg",
    fuel: "Petrol",
    transmission: "Manual",
    engine: "310cc",
    description: "Performance-oriented sports bike with aggressive design.",
    features: ["Liquid Cooled", "ABS", "Digital Console", "Alloy Wheels"],
    variants: [
      { name: "Standard", price: 280000, transmission: "Manual" },
      { name: "Race Edition", price: 310000, transmission: "Manual" },
    ],
    colors: ["Racing Red", "Matte Black", "Pearl White", "Stealth Grey"],
    galleryImages: [
      "/tvs-apache-rr310-sport-bike.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    specifications: {
      bodyType: "Sports",
      engineType: "Single Cylinder, Liquid Cooled",
      power: "34.1 bhp",
      torque: "27.3 Nm",
      brakeType: "Disc + Disc",
      tyreFront: "100/80-17",
      tyreRear: "130/70-17",
      seatHeight: "800mm",
      fuelTankCapacity: "17.3L",
    },
  },
]
